name = "AI&IoT Research Lab"
license = "MIT"
licenselink = "https://github.com/CSIRCMERI/csircmeri.github.io/blob/main/LICENSE.md"
description = "The **AI&IoT Lab website** empowers your research group to easily create a beautiful website with a stunning homepage, news, academic publications, events, team profiles, and a contact form."
homepage = "https://github.com/CSIRCMERI/csircmeri.github.io"
demosite = "https://aiiot.netlify.app/"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Arnab Mallick"
  homepage = "https://aiiot.netlify.app/author/arnab-mallick/"
